import type { ReactNode } from "react";
import {
  FiServer,
  FiShield,
  FiUploadCloud,
  FiWifi,
  FiUsers,
  FiTool,
} from "react-icons/fi";
import {
  SiReact,
  SiNextdotjs,
  SiTypescript,
  SiFramer,
  SiTailwindcss,
  SiAxios,
  SiDotnet,
  SiEjs,
  SiFirebase,
  SiFlask,
  SiGnubash,
  SiKalilinux,
  SiMongodb,
  SiNodedotjs,
  SiPython,
  SiUnity,
  SiExpress,
  SiGo,
  SiJavascript,
  SiPostgresql,
  SiDocker,
} from "react-icons/si";

export const tagIcons: Record<string, ReactNode> = {
  React: <SiReact />,
  "Next.js": <SiNextdotjs />,
  TypeScript: <SiTypescript />,
  "Framer Motion": <SiFramer />,
  "Tailwind CSS": <SiTailwindcss />,
  "Node.js": <SiNodedotjs />,
  Express: <SiExpress />,
  MongoDB: <SiMongodb />,
  Multer: <FiUploadCloud />,
  EJS: <SiEjs />,
  Axios: <SiAxios />,
  Unity: <SiUnity />,
  "C#": <SiDotnet />,
  "Firebase Realtime DB": <SiFirebase />,
  "Firebase Auth": <SiFirebase />,
  "Backend services": <FiServer />,
  "Kali Linux": <SiKalilinux />,
  Bash: <SiGnubash />,
  "Aircrack-ng": <FiWifi />,
  Hashcat: <FiShield />,
  Flask: <SiFlask />,
  Python: <SiPython />,
  Go: <SiGo />,
  JavaScript: <SiJavascript />,
  PostgreSQL: <SiPostgresql />,
  Docker: <SiDocker />,
  "Dev Container": <FiTool />,
  "HR Module": <FiUsers />,
};

export const tagColors: Record<string, string> = {
  React: "text-sky-400",
  "Next.js": "text-zinc-100",
  TypeScript: "text-sky-300",
  "Framer Motion": "text-pink-300",
  "Tailwind CSS": "text-teal-300",
  "Node.js": "text-green-400",
  Express: "text-zinc-200",
  MongoDB: "text-emerald-400",
  Multer: "text-orange-300",
  EJS: "text-yellow-300",
  Axios: "text-blue-200",
  Unity: "text-white",
  "C#": "text-indigo-300",
  "Firebase Realtime DB": "text-amber-300",
  "Firebase Auth": "text-amber-300",
  "Backend services": "text-red-200",
  "Kali Linux": "text-cyan-300",
  Bash: "text-lime-300",
  "Aircrack-ng": "text-sky-200",
  Hashcat: "text-rose-300",
  Flask: "text-emerald-200",
  Python: "text-yellow-200",
  Go: "text-cyan-300",
  JavaScript: "text-amber-300",
  PostgreSQL: "text-sky-300",
  Docker: "text-blue-300",
  "Dev Container": "text-indigo-300",
  "HR Module": "text-rose-200",
};
